version: '3'
services:
  backend-app:
    image: node:fermium-buster
    container_name: ts-web-console-sample-api
    working_dir: /home/ts-web-console-sample-api
    ports:
      - 3001:3001
    tty: true
    volumes:
      - .:/home/ts-web-console-sample-api
      - node_modules_volume:/home/ts-web-console-sample-api/node_modules
    env_file:
      - ./docker/backend_app/env_files/development.env
    networks:
      - web-console-sample

volumes:
  node_modules_volume:

networks:
  web-console-sample:
    external: true
