version: '3'

# Environment variables for mysql database
x-mysql-database: &MYSQL_DATABASE devdb
x-mysql-user: &MYSQL_USER devuser
x-mysql-password: &MYSQL_PASSWORD devdev

services:
  backend-app:
    image: node:fermium-buster
    container_name: ts-web-console-sample-api
    working_dir: /home/ts-web-console-sample-api
    ports:
      - 3001:3001
    tty: true
    volumes:
      - .:/home/ts-web-console-sample-api
      - node_modules_volume:/home/ts-web-console-sample-api/node_modules
    env_file:
      - ./docker/backend_app/env_files/development.env
    networks:
      - web-console-sample
  mysqldb-local:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: ts-web-console-sample-mysql
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_USER: *MYSQL_USER
      MYSQL_PASSWORD: *MYSQL_PASSWORD
    networks:
      - web-console-sample

volumes:
  node_modules_volume:

networks:
  web-console-sample:
    external: true
