version: 2.1

orbs:
  node: circleci/node@4.2.1
  codecov: codecov/codecov@1.1.3

workflows:
  build-and-test:
    jobs:
      - node/test:
          version: 14.16.1
          pkg-manager: yarn
          run-command: coverage
          post-steps:
            - store_artifacts:
                path: coverage
            - codecov/upload:
                file: ./coverage/lcov.info
